namespace Api.DTOs;

public record DoctorDto(
    Guid Id,
    string FirstName,
    string LastName,
    string? DisplayName,
    string? FullName,
    string? Email,
    string? Phone,
    string? Mobile,
    List<string> Languages,
    string? Qualifications,
    string? Biography,
    bool IsActive,
    DateTime CreatedAt,
    // Operational fields
    string? Nationality,
    string? Classification,
    string? InsuranceAcceptance,
    string? InsuranceNotes,
    string? AvailabilityStatus,
    string? CoordinatorName,
    string? InternalExtension,
    string? WorkingHours,
    string? WorkingDays,
    string? AgeGroup,
    decimal? ConsultationFee,
    string? Services,
    string? ClinicMechanism,
    string? Notes,
    // Related entities
    Guid BranchId,
    string BranchName,
    Guid SpecialtyId,
    string SpecialtyName,
    Guid SectorId,
    string SectorName
);

public record CreateDoctorRequest(
    string FirstName,
    string LastName,
    string? DisplayName,
    string? Email,
    string? Phone,
    string? Mobile,
    List<string>? Languages,
    string? Qualifications,
    string? Biography,
    string? Nationality,
    string? Classification,
    string? InsuranceAcceptance,
    string? InsuranceNotes,
    string? AvailabilityStatus,
    string? CoordinatorName,
    string? InternalExtension,
    string? WorkingHours,
    string? WorkingDays,
    string? AgeGroup,
    decimal? ConsultationFee,
    string? Services,
    string? ClinicMechanism,
    string? Notes,
    Guid BranchId,
    Guid SpecialtyId,
    Guid SectorId
);

public record UpdateDoctorRequest(
    string? FirstName,
    string? LastName,
    string? DisplayName,
    string? Email,
    string? Phone,
    string? Mobile,
    List<string>? Languages,
    string? Qualifications,
    string? Biography,
    string? Nationality,
    string? Classification,
    string? InsuranceAcceptance,
    string? InsuranceNotes,
    string? AvailabilityStatus,
    string? CoordinatorName,
    string? InternalExtension,
    string? WorkingHours,
    string? WorkingDays,
    string? AgeGroup,
    decimal? ConsultationFee,
    string? Services,
    string? ClinicMechanism,
    string? Notes,
    Guid? BranchId,
    Guid? SpecialtyId,
    Guid? SectorId,
    bool? IsActive
);
